---
# Installation de Apache
- name: Installation
  ansible.builtin.yum:
    name:
      - httpd
    state: present
  when: ansible_distribution == "CentOS"

- name: Desactivation SELinux
  ansible.posix.selinux:
    policy: targeted
    state: permissive

- name: Ouverture du port 80
  ansible.posix.firewalld:
    port: 80/tcp
    immediate: true
    permanent: true
    state: enabled

- name: Copie du fichier index.html
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
    owner: ansible
    group: ansible
    mode: 0644

- name: Lancement du service Apache
  systemd:
    name: httpd
    state: started
    enabled: yes
...