---
- name: Mon playbook de deploiement
  hosts: prod
  #become: yes
  vars_files:
    - files/secrets/credentials.vault
  tasks:
  - name: Installation de curl git et apache
    ansible.builtin.yum:
      name:
        - curl
        - git
        - httpd
      state: present
    when: ansible_distribution == "CentOS"

  - name: Desactivation SELinux
    ansible.posix.selinux:
      policy: targeted
      state: permissive

  - name: "Ouvrir le port 80"
    ansible.posix.firewalld:
      port: 80/tcp
      immediate: true
      permanent: true
      state: enabled

  - name: Copie du fichier index.html
    template:
      src: index.html.j2
      dest: /var/www/html/index.html
      owner: choco
      group: choco
      mode: 0644

  - name: Lancement du service Apache
    systemd:
      name: httpd
      state: started
      enabled: yes
...